[package]
name = "qiskit-passmanager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "qiskit_passmanager"
doctest = false

[lints]
workspace = true

[dependencies]
smallvec.workspace = true
anyhow.workspace = true
thiserror.workspace = true
hashbrown.workspace = true

[dev-dependencies]
qiskit-circuit = { workspace = true, features = ["passmanager"] }
qiskit-transpiler.workspace = true
