version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns: ['*']
    labels:
      - "Rust"
      - "dependencies"
      - "Changelog: None"
    ignore:
      # faer has historically made major breaking changes between minor versions, so it's easier to
      # do things manually ourselves.
      - { dependency-name: "faer", versions: [">0.19.4"] }
      - { dependency-name: "faer-ext", versions: [">0.2.0"] }
      # nalgebra 0.34 bumped its MSRV to 1.87, which is too high for us.
      - { dependency-name: "nalgebra", versions: [">0.33.2"] }
      # Used by the experimental OQ3 exporter at a time when we were expecting to make updates
      # manually to this.
      - { dependency-name: "oq3_semantics", versions: [">0.0.7"] }
      # hashbrown 0.13.0 bumped the MSRV to 1.61
      - { dependency-name: "hashbrown", versions: [">0.12.3"] }

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      GitHub_Actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: weekly
    labels:
      - "type: qa"
      - "dependencies"
      - "Changelog: None"
    ignore:
      # This semi-reliably requires us to make manual changes to the wheel-build rules, so it's more
      # convenient to do it all ourselves.
      - { dependency-name: "pypa/cibuildwheel", versions: [">3.0.1"] }
