version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # When we use crates that depend on PyO3, we all have to agree on the version used, so they
      # need to be bumped as one group.  Typically, minor-version bumps of PyO3 will require manual
      # intervention, but it's still helpful to have Dependabot prod us to do it.
      pyo3:
        patterns:
          - "pyo3"
          - "numpy"
        update-types:
          - "major"
          - "minor"
      cargo:
        patterns: ['*']
    labels:
      - "Rust"
      - "dependencies"
      - "Changelog: None"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      GitHub_Actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: weekly
    labels:
      - "type: qa"
      - "dependencies"
      - "Changelog: None"
    ignore:
      # This semi-reliably requires us to make manual changes to the wheel-build rules, so it's more
      # convenient to do it all ourselves.
      - { dependency-name: "pypa/cibuildwheel", versions: [">3.0.1"] }
      # The version of this is used as a cutesy way to select the Rust version instead of doing
      # things with an Actions input.
      - { dependency-name: "dtolnay/rust-toolchain", versions: [">1.7.0"] }
