[package]
name = "qiskit-qasm2"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "qiskit_qasm2"
doctest = false

[lints]
workspace = true

[features]
default = ["py"]
py = ["dep:pyo3", "dep:qiskit-circuit"]

[dependencies]
num-bigint.workspace = true
hashbrown.workspace = true

[dependencies.pyo3]
workspace = true
optional = true
features = ["py-clone", "num-bigint"]

[dependencies.qiskit-circuit]
workspace = true
optional = true