// This code is part of Qiskit.
//
// (C) Copyright IBM 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

//! Rust bindings to the raw Qiskit C API, accessed through the Python-space `qiskit` package.
//!
//! This is a low-level, mostly automatically generated, crate.  All the functions (with the
//! exception of [`qk_import`]) are unsafe, since they rely on [`qk_import`] having been called
//! (successfully!) before any of them are valid.
//!
//! You should also consult the [documentation of the Qiskit C API][qiskit-capi], which is the
//! canonical version of the C API documentation.  All the functions, structs, and enums listed here
//! are derived directly from the same source as the C API documentation.
//!
//! You may find the [Qiskit C API documentation on creating Python extension modules in
//! C][extend-qiskit-with-c] useful as a guide to using the C API.
//!
//! [qiskit-capi]: https://quantum.cloud.ibm.com/docs/api/qiskit-c
//! [extend-qiskit-with-c]: https://quantum.cloud.ibm.com/docs/guides/c-extension-for-python
//!
//! # Export conventions
//!
//! ## Enums
//!
//! C does not have namespacing, so in the raw C API, all enum values are prefixed with the name
//! of the enum (such as
//! [`QkExitCode_Success`](https://quantum.cloud.ibm.com/docs/api/qiskit-c/qk-exit-code)).  In Rust,
//! we instead export them using natural namespacing, such as [`QkExitCode::Success`].
//!
//! All Qiskit C API enums are simple integer representations, so ours derive the standard-library
//! derivations (`Clone`, `Copy`, etc).
//!
//! ## Structs
//!
//! Fully defined C structs are declared in the natural way one would expect from C: all fields are
//! `pub`, all fields have their documented names, and the struct is `#[repr(C)]`.  The structs do
//! not derive anything other than `Debug`.
//!
//! Opaque structs are defined as unconstructable invariant pinned objects, [as suggested by the
//! Rustonomicon](https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs).
//!
//! ### Exceptions
//!
//! `QkComplex64` is exposed directly as [`num_complex::Complex64`], which it is necessarily ABI
//! compatible with (in order to interoperate with C/C++ correctly), and is how the object is
//! actually defined by Qiskit too.
//!
//! ## Functions
//!
//! All C API functions are exposed directly using the same naming conventions and call signatures
//! as stated in the C API documentation.
//!
//! *Note*: the functions exposed by [`qiskit-pyo3-ffi`] are not the raw `extern "C"` functions of
//! the Qiskit C API; they are `#[inline] extern "Rust"` wrappers around suitable function-pointer
//! dereferencing.
//!
//! ### Exceptions
//!
//! [`qk_import`] is not a native-library C API function (just as it isn't in the C header file
//! either), and requires a PyO3 [`Python`] token to call.
//!
//!
//! # Safety
//!
//! All function calls (other than of [`qk_import`] itself) are *invalid* until [`qk_import`] has
//! been called successfully.  You will typically want to do this in your Python module
//! initialization.
//!
//! Note also that the "safety" documentation of individual functions (and of the usage patterns of
//! structs) is incomplete; you should consult the [Qiskit C API documentation][qiskit-capi] for the
//! relevant function for all the pre- and post-conditions.

// The complete version of this module is autogenerated.
#[rustfmt::skip]
mod ffi;

use pyo3::prelude::*;
use pyo3::types::PyCapsule;
use std::ffi::{CString, c_void};
use std::ptr::NonNull;
use std::sync::OnceLock;

pub use ffi::*;

/// Simple wrapper around a pointer we know should be safe to share between threads.
#[derive(Clone, Copy, Debug)]
#[repr(transparent)]
struct VTablePtr(NonNull<*mut c_void>);
impl std::ops::Deref for VTablePtr {
    type Target = NonNull<*mut c_void>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
// Raw pointers aren't `Send` or `Sync`, but this is more of a lint to prevent data structures that
// contain them from accidentally auto-deriving `Send + Sync`.  In our case, we trust that neither
// Qiskit nor Python will invalidate the pointers stored in the `PyCapsule`s at any point (and we
// leak a reference to each capsule to make sure the capsules themselves stick around).
unsafe impl Send for VTablePtr {}
unsafe impl Sync for VTablePtr {}

static CAPI_MODULE_NAME: &str = "qiskit._accelerate.capi";

// `qk_import` stores the vtable pointers from each of the corresponding `PyCapsule`s of the C API
// into these statics, then the `declare_fn!` macro is used (in the generated `ffi` module) to wrap
// each entry in an inline Rust function that accesses it.
static QK_FFI_CIRCUIT: OnceLock<VTablePtr> = OnceLock::new();
static QK_FFI_TRANSPILE: OnceLock<VTablePtr> = OnceLock::new();
static QK_FFI_QI: OnceLock<VTablePtr> = OnceLock::new();

/// Prepare the Qiskit C API for use.
///
/// This *must* be called before any raw FFI functions are called.  All Qiskit C API functions
/// accessed through this crate are invalid before this has succeeded.
///
/// In general, you should call this during the Python module initialization function of any
/// submodule you create, such as:
///
/// ```rust,ignore
/// #[pyo3::pymodule]
/// mod my_module {
///     use pyo3::prelude::*;
///     use qiskit_pyo3_ffi as ffi;
///
///     #[pymodule_init]
///     fn init(m: Bound<'_, PyModule>) -> PyResult<()> {
///         ffi::qk_import(m.py())?;
///         Ok(())
///     }
/// }
/// ```
///
/// It is safe to call this function more than once.
pub fn qk_import(py: Python) -> PyResult<()> {
    let capsules = [
        (&QK_FFI_CIRCUIT, "QK_FFI_CIRCUIT"),
        (&QK_FFI_TRANSPILE, "QK_FFI_TRANSPILE"),
        (&QK_FFI_QI, "QK_FFI_QI"),
    ];
    for (lock, name) in capsules {
        // This is a lazy approximation of `get_or_try_init`, which isn't stable in Rust 1.80.  If
        // more than one thread is attempting to do `qk_import` simultaneously, then the caller is
        // doing something very weird, but it shouldn't be a problem for us because Python is
        // responsible for making sure the import system is thread safe.
        //
        // We don't care about duplicating work because a) it's fairly cheap work and there's a
        // clear single-threaded program point to call it at (module import), and b) the
        // `PyCapsule`s _must_ have the same pointer in at all times even if accessed multiple times
        // or all the vtable lookups even within a single thread would be broken.
        if lock.get().is_none() {
            // We don't use `PyCapsule::import` so we can deliberately leak the Python reference to
            // it, making it immortal.
            let capsule = py
                .import(CAPI_MODULE_NAME)?
                .getattr(name)?
                .cast_into::<PyCapsule>()?;
            let fullname = CString::new(format!("{CAPI_MODULE_NAME}.{name}"))
                .expect("our static values should not contain nul");
            let ptr = capsule
                .pointer_checked(Some(&fullname))?
                .cast::<*mut c_void>();
            // We don't care about the error of another thread beating us to set the value; the
            // value should be the same from every calculation or we've got worse problems.
            if lock.set(VTablePtr(ptr)).is_ok() {
                // Make the capsule immortal by leaking a reference.  In theory this shouldn't
                // actually matter, because Qiskit shouldn't ever be invalidating its capsules, but
                // in that case this has no effect so it's safe anyway.  (This also doesn't prevent
                // somebody from overwriting the pointer in the capsule, but there's not much we can
                // do about that if it happens and we won't see the update anyway.)
                std::mem::forget(capsule);
            }
        }
    }
    Ok(())
}

/// Declare a C API function in a given `vtable` at a given `offset`.  The syntax is
/// ```
/// declare_fn!(vtable[offset]; fn_name(arg_list) -> return_type);
/// ```
/// where the second argument looks like a Rust function signature.  For example:
/// ```
/// declare_fn!(QK_FFI_CIRCUIT[5]; qk_circuit_new(num_qubits: u32, num_clbits: u32) -> *mut QkCircuit);
/// ```
///
/// All the calls to this are autogenerated.
macro_rules! declare_fn {
    (
        $vtable:path[$offset:expr];
        $fn_name:ident ( $($arg_name:ident : $arg_ty:ty),* ) $(-> $ret_ty:ty)?
    ) => {
        /// See docs for
        #[doc = concat!("`", stringify!($fn_name), "`")]
        /// in the Qiskit C API for full information.
        ///
        /// # Safety
        ///
        /// `qk_import` must have been called and returned successfully within the process before
        /// this function is called.  Typically this should be done in a PyO3 module initializer.
        ///
        /// See the [Qiskit C API documentation](https://quantum.cloud.ibm.com/docs/api/qiskit-c)
        /// for any other safety requirements.
        #[inline(always)]
        pub unsafe fn $fn_name( $($arg_name: $arg_ty),* ) $( -> $ret_ty )? {
            // SAFETY: per documentation, caller is reponsible for ensuring that `qk_import` was
            // called before any API functions.
            let __vtable = unsafe { $vtable.get().unwrap_unchecked() };
            // SAFETY: per `qk_import` and Qiskit documentation, the stored pointer is valid for
            // all vtable accesses to Qiskit C API functions.
            let __fptr = unsafe { __vtable.add($offset) }.as_ptr();
            let __fptr = __fptr as *const extern "C" fn($($arg_ty),*) $( -> $ret_ty )?;
            // SAFETY: per `qk_import` and Qiskit documentation, the function pointer is valid and
            // has a known type.
            unsafe { (*__fptr)($($arg_name),*) }
        }
    }
}
pub(crate) use declare_fn;
