---
performance:
  - The internal linear-algebra library used by :class:`.TwoQubitBasisDecomposer`
    and :class:`.TwoQubitWeylDecomposition` is now
    `nalgebra <https://docs.rs/nalgebra/latest/nalgebra/>`__.
    This provides stack allocations and optimized operations for small matrices.
    Both passes are now more performant and use less memory.
    See `#15928 <https://github.com/Qiskit/qiskit/pull/15928>`__ and
    `#15960 <https://github.com/Qiskit/qiskit/pull/15960>`__ for more details.
