#!/bin/bash

# This code is part of Qiskit.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
set -e
set -x

function usage {
    echo "usage: ${BASH_SOURCE[0]} -p /path/to/qiskit/python <qpy_version> <version>" 1>&2
    exit 1
}

python="python"
while getopts "p:" opt; do
    case "$opt" in
        p)
            python="$OPTARG"
            ;;
        *)
            usage
            ;;
    esac
done
shift "$((OPTIND-1))"
if [[ $# != 2 ]]; then
    usage
fi

# `qpy_version` is the version of the tested qpy files. `version` is
# the source version: the release with which attempt to load the qpy files under test.

qpy_version="$1"
qiskit_version="$2"
# Get the development version
qiskit_venv="$(pwd -P)/venvs/dev"
qiskit_python="$qiskit_venv/bin/python"
dev_version="$("$qiskit_python" -c 'import qiskit; print(qiskit.__version__)')"
echo "Running on qpy_version $qpy_version, qiskit version $qiskit_version, with dev version $dev_version"

files_dir="$(pwd -P)/forward-qpy-files/qpy${qpy_version}"
our_dir="$(realpath -- "$(dirname -- "${BASH_SOURCE[0]}")")"
venv_dir="$(pwd -P)/venvs/qiskit-$qiskit_version"

if [[ ! -d "$files_dir" ]]; then
    echo "Error: QPY files directory not found: $files_dir" 1>&2
    echo "Please run run_tests.sh first to generate QPY files" 1>&2
    return 1
fi

# Step 1: Create virtual environment with the old Qiskit release.
echo "Building venv for qiskit==$qiskit_version"
"$python" -m venv "$venv_dir"
"$venv_dir/bin/pip" install --upgrade pip setuptools wheel
"$venv_dir/bin/pip" install -c "${our_dir}/qpy_test_constraints.txt" "qiskit==${qiskit_version}" packaging

# Step 2: Load the pre-generated QPY files using the venv.
pushd "$files_dir"
echo "Loading QPY $qpy_version files generated by dev version==$dev_version with qiskit==$qiskit_version"
"$venv_dir/bin/python" "${our_dir}/test_qpy.py" load --version="$dev_version" --qpy-version="$qpy_version" \
    || { rm -rf "$venv_dir"; exit 1; }
popd

# Step 3: Clean up virtual environment.
rm -rf "$venv_dir"