// This code is part of Qiskit.
//
// (C) Copyright IBM 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

#if !defined(QISKIT_H)
#define QISKIT_H

#if defined(QISKIT_C_PYTHON_INTERFACE) || defined(QISKIT_PYTHON_EXTENSION)
#include <Python.h>
#endif // defined(QISKIT_C_PYTHON_INTERFACE) || defined(QISKIT_PYTHON_EXTENSION)

#include "qiskit/attributes.h"
#include "qiskit/complex.h"
#include "qiskit/version.h"

#include "qiskit/types.h" // Generated by cbindgen.

#if defined(QISKIT_PYTHON_EXTENSION)
#include "qiskit/funcs_py.h" // Generated by Qiskit's `pyext` (or stubbed out).
#else
#include "qiskit/funcs.h" // Generated by cbindgen.
#endif                    // QISKIT_PYTHON_EXTENSION

#endif // QISKIT_H
