---
name: C API Tests
on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to test.
        type: string
        required: true
      runner: 
        description: Runner image to use.
        type: string
        required: true

jobs:
  tests:
    name: ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Run tests
        run: make ctest
