---
name: Docs
on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to test.
        type: string
        required: true
      runner: 
        description: Runner image to use.  Expects an Ubuntu image.
        type: string
        required: true

jobs:
  docs:
    name: Docs
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          # We need to fetch the whole history so 'reno' can do its job and we can inspect tags.
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install ubuntu docs dependencies
        run: tools/install_ubuntu_docs_dependencies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run docs
        run: tox -e docs
      - name: Clean up docs detritus
        run: rm -rf docs/_build/html/{.doctrees,.buildinfo}
      - name: Store built documentation artifact
        uses: actions/upload-artifact@v7
        with:
          name: qiskit-docs
          path: |
            ./docs/_build/html/*
          if-no-files-found: error
