---
name: Test Windows
on:
  workflow_call:
    inputs:
      python-version:
        description: >
          Python version to currently test
        type: string
        required: true
      runner:
        description: >
          Describes the system this workflow should run on.
        type: string
        required: true
      install-optionals:
        description: >
          Decides whether we install optyional dependencies
        type: boolean
        default: false
      mimalloc:
        description: >
          Whether to build with mimalloc or not
        type: boolean
        default: true
jobs:
  test-windows:
    name: ${{ inputs.runner }} - Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 60
    env:
      QISKIT_TEST_CAPTURE_STREAMS: 1
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}
      - name: Cache stestr
        uses: actions/cache@v6
        with:
          key: 'stestr | "${{ runner.os }}" | "${{ inputs.python-version }}" | "${{ github.run_id }}"'
          restore-keys: |
            stestr | "${{ runner.os }}" | "${{ inputs.python-version }}"
            stestr | "${{ runner.os }}"
            stestr
          path: .stestr
      - name: Set mimalloc for build
        if: ${{ inputs.mimalloc }}
        run: 'echo "QISKIT_BUILD_WITH_MIMALLOC=1" >> $GITHUB_ENV'
      - name: Install dependencies
        run: |
          set -e
          python -m venv test-job
          source ./test-job/Scripts/activate
          python -m pip install -U pip
          python -m pip install -U \
            -c constraints.txt \
            --group test \
            ${EXTRA_GROUPS} \
            -e .
        shell: bash
        env:
          EXTRA_GROUPS: ${{ inputs.install-optionals && '--group optionals-all' || '' }}
      - name: Run Tests
        run: |
          set -e
          source ./test-job/Scripts/activate
          python tools/report_numpy_state.py
          export PYTHONHASHSEED=$(python -S -c "import random; print(random.randint(1, 1024))")
          echo "PYTHONHASHSEED=$PYTHONHASHSEED"
          stestr run --slowest --abbreviate
        shell: bash
        env:
          QISKIT_PARALLEL: FALSE
          QISKIT_IGNORE_USER_SETTINGS: TRUE
          RUST_BACKTRACE: 1
      - name: Filter stestr history
        run: |
          .\test-job\Scripts\activate
          stestr history remove all
      - name: Copy and Publish images
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: copied-images-${{ runner.name }}-tests-Python-${{ inputs.python-version }}
          path: "**/*.png"
          if-no-files-found: error
